mod 'puppetlabs/apache'
mod 'puppetlabs/stdlib'
mod 'puppet/php'
mod 'puppetlabs/concat'
mod 'puppetlabs/apt'
mod 'puppetlabs/inifile'
mod 'puppet/archive'
mod 'puppet-nginx', '3.3.0'
mod 'camptocamp/systemd'